### ISSUE TITLE
data snapshot loses class information

### ISSUE THREAD

**Issue by thorning** [HerringtonDarkholme/av-ts#10]
```
class Test {

}

class TestComponent extends Vue {
  test:Test = new Test();
}
```

Here the class info is lost at runtime, and `test` property on the component is a simple object.

This means that it will fail a check if used as a property that expect a specific type.

```
@Prop test = p({
    type:Test
  })
```

Current workaround is to either use a data function to avoid the snapshotting, or set the property type `Object`

**Comment by HerringtonDarkholme** [comment]
No, non-plain object is not recommended by vue. I cannot know which constructor you use.

**Comment by thorning** [comment]
I see. After reading the section in the Vue documentation [](https://vuejs.org/api/#data) I think a better approach for this is using plan objects and typescript interfaces.
