### ISSUE TITLE
av-ts should not proxy private members to Vue's data object

### ISSUE THREAD

**Issue by oliverw** [HerringtonDarkholme/av-ts#12]
First of all thanks a lot for this excellent solution for us vuejs-ts developers.

One thing that I would like to see is making it possible to opt out of proxying fields to Vue.js's data section by simply declaring them private. I haven't spend enough time with TS's decorators to be sure if that's even possible.

**Comment by HerringtonDarkholme** [comment]
Hi @oliverw, thanks for trying av-ts. 

According to the design of TypeScript, type level information like `private` accessibility is only preserved at compile time. That said, opting out by `private` keyword is impossible.

I wonder how can you opt out for `data` section. The runtime semantic of class is almost the same as declaring vue in plain object style. If you don't want to put it in data section, then it means you cannot use it at runtime anyway.

If you just don't want Vue to watch some properties' change, you can just prefix it `_` or `$`.  Reference: https://vuejs.org/v2/api/#data

**Comment by oliverw** [comment]
Fair enough. 

The sole reason for coming up with the idea was my confusion when starting to learn vue.js. I had a member of component class that was an RxJs Observable which got initialized in the constructor and later on had it's prototype chain trashed when Vue.js made it reactive. Later on why I was trying to use the member I got mysterious crashes that took me a while to figure out. 

Now, I know that we arent's supposed put complex objects in the the data section but since it happens by default, it might confuse other people as well :)
