### ISSUE TITLE
Does av-ts support multiple possible types definition of property- union type support in `@Prop`

### ISSUE THREAD

**Issue by thatbin** [HerringtonDarkholme/av-ts#15]
Hi,
We can define mutiple possible types property in Vue like below.

```
Vue.component('example', {
    propB: [String, Number],
})
```

How to use `@Prop` to define it.

**Comment by HerringtonDarkholme** [comment]
You have to fallback to defining a property in component meta and declare it in class body. The type definition for `p([String, Number])` might be supported for future.

For now:

```ts
@Component({
  props: {
   propB: [String, Number]
  }
})
class Example extends Vue {
   propB: string | number
}
```

**Comment by HerringtonDarkholme** [comment]
Hmm, I have looked around the code. It seems to support union types in `@Prop` will require too many overloading resolutions. You can look at how `p` is typed now. And this is not possible for option object style prop declaration.

```ts
@Prop myProp = p({
  type: [String | Number]
}) // tsc cannot infer myProp to string | number
``` 

Also, a union type is not a good practice in my mind. It enables a flexible API for end users, but I would argue it is bad for you application code. If you do need them, adding more verbose configuration for union typed property makes sense in that it discourage usage.

I will close this issue for now. If you can find more real life example that make use multi-typed props. Feel free to comment below.

**Comment by thatbin** [comment]
@HerringtonDarkholme thank you for you prompt reply.
Actually, union type is not so good. I will avoid using it.
