### ISSUE TITLE
Mixin Error

### ISSUE THREAD

**Issue by thatbin** [HerringtonDarkholme/av-ts#16]
I'm trying to use `Mixin`, but I got a error.

> ERROR in D:\somedirectory\Button.ts
> (13,22): error TS2507: Type 'Cls<MA, MB>' is not a constructor function type.

This is my code.

```typescript
import { Vue, Component, Prop, p, Mixin, Trait } from "av-ts";

@Trait class MA extends Vue {
    data1 = 123;
    myMethod() {};
}
@Trait class MB extends Vue {
    data2 = 456;
    myMethod2() {};
}

@Component
class Button extends Mixin(MA, MB) {
}

export = Button;

```

My typescrpt version is 2.0.10.

Mixin(MA, MB) will return a `VueComponent` normally, if I just call it.

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting this. I'm looking on it.

**Comment by HerringtonDarkholme** [comment]
So sorry I only tested runtime behavior but not compiler behavior. It seems users have to write some interface to use Mixin as constructor...

https://github.com/nch3v/typescript-mixins/blob/master/src/duck.ts

**Comment by HerringtonDarkholme** [comment]
Related https://github.com/Microsoft/TypeScript/issues/10261

**Comment by HerringtonDarkholme** [comment]
I have published 0.5.2 which fixed the mixin.
Sorry for the delay. You can read the doc and test cases for examples.

**Comment by thatbin** [comment]
Great! Thanks for your work.  :+1:

**Comment by HerringtonDarkholme** [comment]
Since https://github.com/Microsoft/TypeScript/pull/13604, Mixin without explicit type cast also works.
