### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by davidmoshal** [HerringtonDarkholme/av-ts#18]
Hi, noticed that your vue-cli template doesn't have one preconfigured.
wondering what the preferred testing framework(s) is/are?

other frameworks have some combintion of :
- nightwatch.js
- jest
- karma
etc.

any preferences? 
would be great if your cli template could be pre-configured

thanks
David

**Comment by HerringtonDarkholme** [comment]
Sorry, I cannot have much opinion on testing. There is no official recommendation for vue, for now.

Personally I use mocha+karma/mocha+jsdom. But I don't know whether it is good enough for every one.

Also, this library is not a full stack solution. It is just a small library for type safety. Users have freedom to choose their favorite testing framework.
