### ISSUE TITLE
Can I Import Typescript from another file?

### ISSUE THREAD

**Issue by johnknott** [HerringtonDarkholme/av-ts#19]
I love this library and have it set up with Webpack according to your blog post, and it all works great, so thanks for that.

The one thing I am missing is the ability to separate out the <script> part of  a web component into a separate .ts file and then import it into the .vue file. I would just do this for larger components where code completion and other editor tooling would be really useful.

I don't suppose you would know how to achieve this do you?  I'm pretty much a newbie in this area ...

**Comment by HerringtonDarkholme** [comment]
Yes, you can.

```vue
<script lang="ts" src="relative/path/to/script">
</script>
```

An example: https://github.com/whitetrefoil/vue-ts-arch/blob/master/src/components/app.component.vue

ts-loader should be enough
