### ISSUE TITLE
Using a js file (like jquery for example)

### ISSUE THREAD

**Issue by gldraphael** [HerringtonDarkholme/av-ts#20]
I get the following error:

> ERROR in ./src/app.ts
> (2,17): error TS2307: Cannot find module './app.vue'.
> 
> ERROR in ./\~/vue-ts-loader!./src/assets/ts/js.ts
> Module not found: Error: Cannot resolve module '\~admin-lte/plugins/jQuery/jquery-2.2.3.min.js' in /Users/gldraphael/projects/projname/src/assets/ts
>  @ ./~/vue-ts-loader!./src/assets/ts/js.ts 2:0-56

I've haven't made any changes to `webpack.config.js`

```javascript
resolve: {
      extensions: ['', '.ts', '.vue', '.js']
  },

  module: {
      loaders: [
          { test: /\.vue$/, loader: 'vue' },
          { test: /\.ts$/, loader: 'vue-ts' },
          // a few more loaders for LESS, fonts, etc.
      ],
  },
  vue: {
    // instruct vue-loader to load TypeScript
    loaders: { js: 'vue-ts-loader', less: 'css!less' },
    // make TS' generated code cooperate with vue-loader
    esModule: true
  }
```

I'm using it from `app.vue` as:
```html
<script src="./assets/ts/js.ts"></script>
```

And `js.ts` just includes the jquery file as:

```javascript
import "~admin-lte/plugins/jQuery/jquery-2.2.3.min.js"
```

**Comment by HerringtonDarkholme** [comment]
Hi, you might need `allowJs` in your tsconfig.json to import javascript file.

**Comment by gldraphael** [comment]
That doesn't help. I noticed `node_modules` is excluded in `tsconfig.json`. Is it because I'm trying to access a javascript file under `node_modules`.

As a temporary fix I put a copy of my javascript files in `src` and I'm able to use it from there - works without any issue. Ideally though, I'd want to reference the bundled files under `node_modules` instead.

**Comment by HerringtonDarkholme** [comment]
> import "~admin-lte/plugins/jQuery/jquery-2.2.3.min.js"

I don't know what's `~` means in your example. There are a lot of possible ways to configure webpack with typescript (and screw them).

If you put the code under src and it works. I guess the problem is webpack and ts-loader does not recognize your path.

**Comment by gldraphael** [comment]
You were right about the `~`. Removing that fixed the issue.

This is all I needed:
```javascript
import 'admin-lte/plugins/jQuery/jquery-2.2.3.min.js'
```
