### ISSUE TITLE
p({ type: Number }) doesn't work.

### ISSUE THREAD

**Issue by whitetrefoil** [HerringtonDarkholme/av-ts#21]
TS v2.1.1, av-ts v0.5.4

```ts
num: number = p({
  type: Number
})
```
cause
```
Error:(15, 3) TS2322:Type 'Number' is not assignable to type 'number'.
  'number' is a primitive, but 'Number' is a wrapper object. Prefer using 'number' when possible.
```
Boolean is similar.
But `p(Number)` works.

**Comment by HerringtonDarkholme** [comment]
Hi, this is an intended behavior. 

In TypeScript, `Number` has the type `NumberConstructor`, and `p(Number)` is a hard coded override resolving to `number`.

But for API like `p({type: Number})`, TypeScript will resolve it using `NumberConstructor`'s construct signature, which resolves to `Number`. Note `number` and `Number` is not compatible.

Just skip the manual annotation, most things will be fine because TS will implicit convert `number` to `Number` and vice versa.

**Comment by whitetrefoil** [comment]
Looks like my next step should be to find how to disable that error during
compilation~

2016年11月28日 17:35，"(´・ω・｀)" <notifications@github.com>写道：

**Comment by HerringtonDarkholme** [comment]
@whitetrefoil  You can just skip manual annotation.

`num = p({type: Number, default: 123})` should work.

**Comment by whitetrefoil** [comment]
@HerringtonDarkholme This line is ok w/o annotation, but it will still be problem when I use these props somewhere else. In my current case, I'll using these props to initialize spin.js, but I'll got the same error when `new Spinner({...})`.

**Comment by HerringtonDarkholme** [comment]
Oh... I see it. But I'm afraid this is unfixable issue.
Try annotate like this 
`num: number = p<any>({type: Number, default: 123})`

**Comment by whitetrefoil** [comment]
Yup, I guess this is the only thing we can do for now… I'm already used to fix everything using <any>… _(:3」∠)_

**Comment by whitetrefoil** [comment]
Just found that code like
```ts
  @Prop show    = <boolean> p({ type: Boolean, default: false })
  @Prop width   = <number> p({ type: Number, default: DEFAULT_WIDTH })
```
works...

**Comment by HerringtonDarkholme** [comment]
It also uses type assertion. But clearly fewer key strokes!

**Comment by HerringtonDarkholme** [comment]
Hi @whitetrefoil 

In case you are still interested, av-ts @0.8.1 shipped a new implementation of `p`.

Now `@Prop show = p({type: Boolean, default: false})` does not need explicit casting!

**Comment by whitetrefoil** [comment]
Nice! Will try the new version tomorrow~
