### ISSUE TITLE
name doesnt show up

### ISSUE THREAD

**Issue by Jack85** [HerringtonDarkholme/av-ts#22]
Hi, 
if I have following template, where my etx ist just exporting all your stuff with with vue, 
I put **name** in component, it doesnt get displayed, shouldnt it?
How is it rendering objects that I fill inside decorator?
Thanks
```

<template>
    <div>
This is ABOUT template..{{someabout}}  {{name}}
    </div>
</template>
<script>
import {Component, create, getHelper,Vue,Vuex }  from '../etx'

@Component({
     name: 'aboutname'
})
export default class about extends Vue {
    someabout = 'about'
}
</script>
```

**Comment by HerringtonDarkholme** [comment]
It should not.

This should show name

```vue

<template>
    <div>
         This is ABOUT template..{{someabout}}  {{name}}
    </div>
</template>
<script>
import {Component,Vue}  from '../etx'

@Component
export default class about extends Vue {
    someabout = 'about'
     name =  'aboutname'
}
</script>
```

**Comment by Jack85** [comment]
Ok, thanks for quick answer..
But If I use it in decorator I would expect it.. 
Since in my case I like using intellisense in decorator and filling some props there
Would be nice to not have to declare it one more time?
