### ISSUE TITLE
Create something like this for Vuex and Vue-Router?

### ISSUE THREAD

**Issue by snaptopixel** [HerringtonDarkholme/av-ts#26]
Thank you so much for the hard work on this library!

Kilimanjaro is nice but I really think annotations like this would be killer for Vuex and Vue-Router. You mention in the doc that it should be possible using Component.register, but to be honest after looking at the current annotation sources it makes my head spin a bit!

It would be awesome if we could do something like this... is it possible?

```ts
@Store
export default class MyStore {
  count = 0;
  
  @Mutation increment(state, props) {
    state.count += props.amount;
  }

  @Action increment ({commit}, props) {
    commit('increment', props);
  }
}

```

**Comment by HerringtonDarkholme** [comment]
Yes it is possible. https://github.com/HerringtonDarkholme/av-ts#componentregister

I'm afraid the comment is the best source for learning the API. Or you have to read through the source code to understand what happened under hood. Expressing what av-ts has done is quite hard.

I'm not sure what's your example want to do. Does it mean those annotated methods **declare** new action/mutation on store, or action/mutation are binded to the component?

**Comment by snaptopixel** [comment]
Thanks for the reply! Yes they would **declare**, basically just a cleaner way to get around the object-literal syntax as you do with `@Component…` granted, that example wasn't totally thought through just an idea.

**Comment by HerringtonDarkholme** [comment]
Ok, I understand what you want now. An alternative way to declare vuex-store? Right?
Then I would recommend you to migrate this issue to kilimanjaro. Component.register is for component decorator, not store.

**Comment by snaptopixel** [comment]
Correct. Thanks for all the info.
