### ISSUE TITLE
Complier error when using `this` in @Watch

### ISSUE THREAD

**Issue by snaptopixel** [HerringtonDarkholme/av-ts#27]
I'm seeing `property 'list' does not exist on type 'Vue'` errors in console, but the resulting code works correctly. Here is a contrived example of the code in question:

```ts
@Component
export default class Avatar extends Vue {
  list = {
    a: 'thing',
    b: 'other'
  };

  @Watch(function(current, previous) {
    const oldValue = this.list[previous];
    const newValue = this.list[current];
  }, {immediate: true})
  watchedProp: string; // 'a', 'b', etc
}
```

**Comment by HerringtonDarkholme** [comment]
https://github.com/HerringtonDarkholme/av-ts/wiki/FAQ#1-watch-scope

Also, new @Watch is out. https://github.com/HerringtonDarkholme/av-ts/blob/master/CHANGELOG.md
