### ISSUE TITLE
Read me typo

### ISSUE THREAD

**Issue by thorning** [HerringtonDarkholme/av-ts#3]
I'm trying out your library, as it seems like a great way to use typescript in vue. I noticed the following when my c/p failed:

under install
```
import {Componet} from 'av-ts'

@Componet
class MyAwesomeComponent {
  // ....
}
```
`Componet` is missing an n

**Comment by HerringtonDarkholme** [comment]
Thanks! fixed via https://github.com/HerringtonDarkholme/av-ts/commit/fd45d911eee572cc430eb268d61eb4f4a1c8cdc8.
