### ISSUE TITLE
Component instance in tests

### ISSUE THREAD

**Issue by asfernandes** [HerringtonDarkholme/av-ts#32]
I see the tests in this project and read Vue documentation about testing, but I'm unable to get the component instance in my tests. Can you please show a direction?

This is what I have:

```ts
export class LoginComponent extends Vue
{
	userName = 'a';
}
```

And in test:

```ts
const vm = new Vue({
	el: document.createElement('div'),
	render: (h) => h(LoginComponent)
}).$mount();

let userName = vm.$el.querySelector('.user-name') as HTMLInputElement;
```

This is ok.

But how I can read userName from the LoginComponent instance data?

Edit: with standard Vue, I would access the data directly in `vm`, but with av-ts it's not there.

**Comment by asfernandes** [comment]
I figured out that some Vue instance have my data, but the way I create the test this instance is not the test's `vm`.

**Comment by asfernandes** [comment]
I was able the do with this workaround:

```ts
const parentVm = new Vue({
	render: (h) => h(LoginComponent)
}).$mount();

let vm = parentVm.$children[0] as LoginComponent;
```

**Comment by HerringtonDarkholme** [comment]
Hi, I think this alternative can also solve your problem.

Every class component is just a syntactical sweet form of `Vue.extend(option)`, so you can

```ts
var vm = (new LoginComponent).$mount('#some-element')
vm.userName // 'a'
```

Because $mount accept an element/selector as argument which is the `el`. https://vuejs.org/v2/api/#vm-mount

**Comment by asfernandes** [comment]
Thank you! In my case I just need this construction without passing the parameter to $mount.

**Comment by pauleveritt** [comment]
Sorry for commenting on a closed issue. Let me know if I should make a new ticket.

I'm using WebStorm and the TypeScript language service. In the above, the vm instance doesn't seem to have a userName. TypeScript can't get to the attribute when used in a test. I believe it thinks the instance is a Vue class instance, not a LoginComponent instance.

If it would help, I can make a new ticket with more information.
