### ISSUE TITLE
Using inject-loader to mock services

### ISSUE THREAD

**Issue by asfernandes** [HerringtonDarkholme/av-ts#33]
As described in this page (http://vue-loader.vuejs.org/en/workflow/testing-with-mocks.html), I tried to use the inject loader.

I used `require('!!vue?inject!...")`, as tried others names (av-ts) does not work.

The code compiles, but mock does not work. Is this project prepared to allow the use of inject-loader as described in vue docs?

**Comment by HerringtonDarkholme** [comment]
Please confirm this is av-ts' problem. Usually, it is caused by other tool chains. If it is av-ts' problem, provide valid reproduction
