### ISSUE TITLE
Would you be willing to make lowercased aliases for the decorators?

### ISSUE THREAD

**Issue by Evertt** [HerringtonDarkholme/av-ts#38]
My personal preference is to have class-decorators like `@Component` capitalized (because class-names are also capitalized) and all other decorators uncapitalized (because property- and method-names are also uncapitalized).

Different developers / companies prefer different styles. If you'd be willing to export every decorator in both its capitalized form and its uncapitalized form then the developer using your library can import whichever fits his style the best.

**Comment by HerringtonDarkholme** [comment]
Adding your own alias is trivial.
