### ISSUE TITLE
template

### ISSUE THREAD

**Issue by mvujica** [HerringtonDarkholme/av-ts#4]
How can I declare template option in component?
Still migrating from vue 1.0 to 2.0, have been using typescript in components without decorators, and used a lot of template: `<div> ...` option in my .ts files.
Can I just declare template=`<div>..`  ?

**Comment by HerringtonDarkholme** [comment]
Hi, I recommend you to use vue's Single File Component. This can be done by git@github.com:HerringtonDarkholme/vue-ts-loader.git.

If you still need template string in ComponentMeta, try this.

```typescript
declare module 'av-ts/dist/src/interface' {
  export interface ComponentMeta {
    template?: string
  }
}
@Component({
  template: '<div>'
})
class V extends Vue {}
```

This is module augmentation that makes `Component` accept template field

**Comment by mvujica** [comment]
Thanks for update, well, I'm using Visual Studio 2015 and I really love code completion and syntax checking for typescript I really don't want to lose that and by using string template I still have single file component without transpiling. 
Could you commit this to main code? I think It's nice feature.

**Comment by HerringtonDarkholme** [comment]
Under consideration.  If you prefer string template, it means your code needs extra overhead of client side compilation and size bloat. But I believe that user experience should overweight developer experience.

I don't want to promote this **by default**. Developer must enable it **explicitly**. So comes the module augmentation.

For now You can use the code above. Putting it in the entry file should apply to the whole project.

**Comment by mvujica** [comment]
Ok I understand your point, but since it is enabled by default in plain js vue and sometimes preferred in original vue documentation (see use of camelCase names) I think It should be promoted to typescript decorators also. Again many thanks for help, now that I can use string template, I will test your library in my project.

**Comment by HerringtonDarkholme** [comment]
Yes, your point is also right. Even Vue's official documentation recommends standalone version for most users. Introducing a new type is a learning obstacle. Also having both ComponentMeta and ComponentOption will require users to augment modules twice.

Thanks for trying av-ts. Looking forward to your feedback.

**Comment by HerringtonDarkholme** [comment]
Hi, I'm considering just pass Vue's option object to `Component`. You can try https://github.com/HerringtonDarkholme/av-ts/commit/2199aaaf0916e90fb59fb8aba67c1699565f6ead this commit. `template` can be directly used.

**Comment by mvujica** [comment]
Is that like in "official" vue-class-component implementation? Than I can use props in Component also, is there a possibility of conflict with @Props decorator?

**Comment by HerringtonDarkholme** [comment]
No, you cannot use props in Component. It will be overwritten by @Props decorators.

**Comment by mvujica** [comment]
Ok, that is fine and many thanks for your time and work. I can't wait to test it later. Should I close the issue?

**Comment by HerringtonDarkholme** [comment]
Fine. And you can also try it in your browser now http://plnkr.co/edit/KHhs7KDye3kwUvM8SNyZ?p=preview

**Comment by mvujica** [comment]
I'm in process of rewriting my vue 1.0 components as vue 2.0 classes with av-ts and everything is fine. 
For future reference:
is this correct syntax for watching props?
`@Watch(function (value) {
        // update logic       
    })
 @Prop
    value = p(String);   `
In my setup it's working fine!

**Comment by mvujica** [comment]
Also one small thing for using props: compiler complains if p is not imported so it should be:
`import { Component, Prop, p, Watch, Lifecycle, Vue } from "av-ts";`
