### ISSUE TITLE
Hey are you okay with me doing this?

### ISSUE THREAD

**Issue by Evertt** [HerringtonDarkholme/av-ts#42]
I created a new package of my fork of your library, so that I could add it as a dependency in my projects like any other library. I'd just like to check if you're okay with it and if you'd maybe like to get a more explicit mention somewhere in the readme?

[Here it is.](https://github.com/Evertt/vue-typescript-decorators)

**Comment by HerringtonDarkholme** [comment]
Go ahead. I will use BSD license.
