### ISSUE TITLE
Problem with Mixin and custom elements e.g. <router-link>

### ISSUE THREAD

**Issue by rheicide** [HerringtonDarkholme/av-ts#43]
It seems custom elements don't work when I use Mixin. Could you please have a look and tell me if I'm doing something wrong?

Foo.ts:
```ts
import {Vue, Trait} from "av-ts";

@Trait
export default class Foo extends Vue {}
```

Bar.ts:
```ts
import Foo from "components/Foo";
import {Mixin, Component} from "av-ts";

interface Mixed extends Foo {}

@Component
export default class Bar extends Mixin<Mixed>(Foo) {}
```

Bar.vue:
```vue
<template>
  <router-link :to="{ name: 'FooBar' }">Go</router-link>
</template>

<script src="./Bar.ts"></script>
```

I got: `[Vue warn]: Unknown custom element: <router-link> - did you register the component correctly?...`

But if Bar.ts is:
```ts
import {Vue, Component} from "av-ts";

@Component
export default class Bar extends Vue {}
```
...then it's fine.

**Comment by HerringtonDarkholme** [comment]
I don't believe the warning is caused by av-ts. 
It warns you about not using vue-router properly. Please check out the vue-router documentation.
Also, a minimal repository for reproduction is desirable.
