### ISSUE TITLE
Something goes wired in v0.7.1

### ISSUE THREAD

**Issue by whitetrefoil** [HerringtonDarkholme/av-ts#47]
```ts
import { Component, Vue }  from 'av-ts'

@Component()
class Test extends Vue {

}
```
Above code works w/ v0.7.0.  But w/ v0.7.1 it raise error:

> Error:(3, 2) TS2345:Argument of type 'typeof Test' is not assignable to parameter of type 'VClass<any>'.
>   Property 'extend' is missing in type 'typeof Test'.

**Comment by HerringtonDarkholme** [comment]
hmmm, I cannot reproduce it. 
Would you like provide a minimal reproduction?

**Comment by whitetrefoil** [comment]
Try this one:
https://github.com/whitetrefoil/vue-ts-arch/tree/sp/av-ts-071
```
yarn
npm run gulp build
```
My env:
* node v7.6.0
* ts v2.2.1
* yarn v0.20.3
* macOS

**Comment by whitetrefoil** [comment]
FYI: I tried to modify the 1st line of `av-ts/dist/index.d.ts` to old version `import Vue = require('vue');` and the error disappeared...

**Comment by HerringtonDarkholme** [comment]
Please use `allowSyntheticDefaultImports`. 

It is recommended by new import style.

**Comment by whitetrefoil** [comment]
Yeah~ I just found that document~
Thx~
