### ISSUE TITLE
Upgrade or relax Vue dependency

### ISSUE THREAD

**Issue by kristianmandrup** [HerringtonDarkholme/av-ts#50]
Looks like some nice additions: https://github.com/Evertt/av-ts :)

**Comment by HerringtonDarkholme** [comment]
No, currently Vue 2.2 adds new incompatible features for av-ts.
If you want to use Vue2.1 please use older version.

**Comment by kristianmandrup** [comment]
Oh? Like which features? Didn't see any mention of this in Readme. 
So is your version Vue 2.2 compatible but not the Evertt fork?
Is it on the Roadmap to make it 2.2 compatible in the near future?
Please add note to Readme to make this clear. Thanks :)

**Comment by HerringtonDarkholme** [comment]
It is an internal feature. Vue has moved computed properties to prototype so it is not compatible.
