### ISSUE TITLE
Static class properties are undefined

### ISSUE THREAD

**Issue by roblav96** [HerringtonDarkholme/av-ts#52]
First off, this lib is the only reason I've come back to vue. Thank you so much for all your effort =]

When creating static properties on a class, all of them return `undefined`.
```typescript
export default class ChartSbar extends Vue {
	static S_QUERY = 'chart.sbar.query'
	static S_ITEMS = 'chart.sbar.items'
	static S_SCROLL = 'chart.sbar.scroll'
	@Avts.Lifecycle
	mounted() {
		console.log('ChartSbar.S_QUERY', ChartSbar.S_QUERY) // undefined
	}
}
```

I notice all the `ts` trickey you've accomplished (well done) so my guess is that has to do something with it. Any idea how to get this working?

Thanks mate!

**Comment by HerringtonDarkholme** [comment]
Good catch.

I will find time to implement this.

**Comment by roblav96** [comment]
No worries, thanks again for this lib!
