### ISSUE TITLE
howto no data props - question

### ISSUE THREAD

**Issue by Jack85** [HerringtonDarkholme/av-ts#55]
hi, 
lets say I want to use some lib that comes with regular vue like validation (vuelidate)
which extends vue and  its outside of data. 
How to simulate same behavior on your component, if its prop or data its not found.

```
export default {
  data () {
    return {
      name: '',
      age: 0
    }
  },
  validations: {
    name: {
      required,
      minLength: minLength(4)
    },
    age: {
      between: between(20, 30)
    }
  }
}
```
https://monterail.github.io/vuelidate/#sub-basic-form

**Comment by HerringtonDarkholme** [comment]
You need to roll out your own decorator. Otherwise, you can just put validations in `@Component({validattions: {}})`

**Comment by Jack85** [comment]
im av-ts 6.3 last compatible with kilimanjaro
If I put it in component I get:
```
 error TS2345: Argument of type '{ validations: { username: { required: any; minLength: any; }; }; }' is not assignable to param
eter of type 'ComponentOptions<Vue>'.
  Object literal may only specify known properties, and 'validations' does not exist in type 'ComponentOptions<Vue>'.
```

```
 @Component({
    validations: {
    username: {
      required,
      minLength: minLength(4)
    }
  }
    })
```

**Comment by HerringtonDarkholme** [comment]
You need to extend vue's ComponentOption type. 

https://github.com/HerringtonDarkholme/av-ts/wiki/FAQ#3-componentmeta-augmentation

**Comment by Jack85** [comment]
ok, Thanks.
