### ISSUE TITLE
Lifecycle methods give error TS1241

### ISSUE THREAD

**Issue by smares** [HerringtonDarkholme/av-ts#56]
Hi! Do you have a working example that uses lifecycle methods? Even if I use the example with just `@Lifecycle beforeCreate() {}` I get the following error:

> error TS1241: Unable to resolve signature of method decorator when called as an expression. Supplied parameters do not match any signature of call target.

**Comment by HerringtonDarkholme** [comment]
What's your ts version?

**Comment by smares** [comment]
2.3

**Comment by smares** [comment]
Got it sorted. I was missing the target configuration option in tsconfig and the default is es3. Works well now with es5 as target.
