### ISSUE TITLE
Some webpack related issue started from v0.8.0

### ISSUE THREAD

**Issue by whitetrefoil** [HerringtonDarkholme/av-ts#63]
TypeError: __WEBPACK_IMPORTED_MODULE_0_vue__ is not a constructor

![image](https://user-images.githubusercontent.com/573851/27893164-b5860744-61c9-11e7-8a24-52ff89571669.png)

v0.7.2 is OK.

**Comment by HerringtonDarkholme** [comment]
It should be fixed in 0.8.2

**Comment by whitetrefoil** [comment]
Verified!
