### ISSUE TITLE
Failing unit tests on PhantomJS since av-ts 0.8.x

### ISSUE THREAD

**Issue by DorianGrey** [HerringtonDarkholme/av-ts#64]
Hi there,

I've recently started to play around with vuejs and typescript, and thus landed on av-ts as well.
Everything worked fine without a hassle. Except from a proper coverage report, even adding some tests was quite easy... until I updated av-ts to 0.8.2 a couple of days ago.
After this update, the tests cannot be executed any longer, and fail with an error message which is not that self-explanatory. The relevant part of the result of `yarn test`:
```
10 07 2017 08:47:20.119:DEBUG [web-server]: serving: /home/linne/Projects/vue-ts-playground/node_modules/karma/static/context.js
10 07 2017 08:47:20.212:DEBUG [phantomjs.launcher]: TypeError: Type error

10 07 2017 08:47:20.212:DEBUG [phantomjs.launcher]:   http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:446
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:446 in decorate
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:454 in Component
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:11867 in __decorate
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:11649
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:11653 in ./node_modules/ts-loader/index.js!./src/inputTest/inputTest.ts
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:20 in __webpack_require__
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:29206 in ./src/inputTest/inputTest.vue
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:20 in __webpack_require__
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:29170 in ./src/inputTest/inputTest.spec.ts
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:20 in __webpack_require__
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:28882 in webpackContext
  :0 in map
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:78 in requireAll
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:80 in ./config/unitTests/index.ts
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:20 in __webpack_require__
  http://localhost:9876/base/index.ts?fbfb608a3cd7eee8d9001eac4e5f35bb243a97a1:63

PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: Type error
  at index.ts:446
```
I've added a branch that illustrates this issue:
https://github.com/DorianGrey/vue-ts-playground/tree/avts-0.8-test-failure
Already tried another version of the 0.8 series, but that failed with an already reported error: https://github.com/HerringtonDarkholme/av-ts/issues/63

The test execution works fine on master using av-ts 0.7.2 (except the code coverage stuff... but that's another problem to solve):
https://github.com/DorianGrey/vue-ts-playground/tree/master

Any ideas about the source of this problem?

**Comment by HerringtonDarkholme** [comment]
Have you ever tried debug it yourself? For example test it in Chrome to reproduce it?

**Comment by DorianGrey** [comment]
I've tried, yes - but it gave even less useful results.
In Chrome (Chromium in my case) and electron, no tests even got executed - the task just fails with code 1:
```

Finished in 0.004 secs / 0 secs @ 10:27:09 GMT+0200 (CEST)

SUMMARY:
✔ 0 tests completed

=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
10 07 2017 10:27:09.783:DEBUG [karma]: Run complete, exiting.
10 07 2017 10:27:09.784:DEBUG [launcher]: Disconnecting all browsers
10 07 2017 10:27:09.791:DEBUG [coverage]: Writing coverage to /home/linne/Projects/vue-ts-playground/test-results/coverage
10 07 2017 10:27:09.855:DEBUG [reporter.junit]: JUnit results written to "/home/linne/Projects/vue-ts-playground/test-results/junit/TESTS-Chromium_58.0.3029_(Ubuntu_0.0.0).xml".
10 07 2017 10:27:09.887:DEBUG [launcher]: Process Chromium exited with code 0
10 07 2017 10:27:09.887:DEBUG [temp-dir]: Cleaning temp dir /tmp/karma-29324556
10 07 2017 10:27:09.901:DEBUG [launcher]: Finished all browsers
error Command failed with exit code 1.
```
The only message I could pick up from the browser console was this:
```
Refused to execute script from 'http://localhost:9876/base/index.ts' because its MIME type ('video/mp2t') is not executable.
```
Which seems to be quite reasonable - considering that the preprocessor failed before (as the message from phantomjs mentioned), the browser attempts to load something it cannot deal with, and refuses to go ahead.
The same happens in firefox. 

Considering the error message from phantomjs, it seems to have something to do with the `decorate` function from the `Component` decorator, which was changed since 0.7.2 in [this commit](https://github.com/HerringtonDarkholme/av-ts/commit/7d51d8a9bf97d4b46d9382b61cad6be512d4e1cf).
I'm a bit confused here - the content from the npm package of 0.8.2 does not seem to match the source.
The core.js in the package looks like this:
```
 function decorate(cls) {
     Component.inDefinition = true;
     cls.prototype._init = util_1.NOOP;
     var instance = null;
     try {
         instance = new cls();
     }
     finally {
         Component.inDefinition = false;
     }
     delete cls.prototype._init;
     var proto = cls.prototype;
     var options = makeOptionsFromMeta(meta, cls['name']);
     var _a = getKeys(proto), internalKeys = _a.internalKeys, normalKeys = _a.normalKeys;
     for (var _i = 0, internalKeys_1 = internalKeys; _i < internalKeys_1.length; _i++) {
         var protoKey = internalKeys_1[_i];
         collectInternalProp(protoKey, proto, instance, options);
     }
     for (var _b = 0, normalKeys_1 = normalKeys; _b < normalKeys_1.length; _b++) {
         var protoKey = normalKeys_1[_b];
         collectMethodsAndComputed(protoKey, proto, options);
     }
     // everything on instance is packed into data
     collectData(cls, Object.keys(instance), options);
     var Super = findSuper(proto);
     return Super.extend(options);
 }
```
While the source code (since the referenced change) performs [some more steps](https://github.com/HerringtonDarkholme/av-ts/blob/master/src/core.ts#L157) after the `findSuper` line.

As I mentioned, the tests executed fine with 0.7.2., and 0.8.2 still works for and both for dev and build tasks. I'm not sure where to go ahead from here.

**Comment by HerringtonDarkholme** [comment]
The error stack is unreadable.
Please consider finding out some meaningful error message.

The possible cause is adding static methods to constructor. But I cannot reproduce. You can try delete those lines in node_module.

**Comment by HerringtonDarkholme** [comment]
This is phantom specific bug. Assigning `arguments` and `caller` will cause, well, a `TypeError` without any useful information.

I won't fix it for a platform where the author has abdicated maintenance.

**Comment by DorianGrey** [comment]
Hm... sounds reasonable. I've debugged things down a bit and was wondering why both `cls['arguments']` and `ret['arguments']` raised a `TypeError` here. I'm not the biggest fan of Phantomjs, just picked it up because it was mentioned as "recommended" in the vue template.
I'll try to go with Electron in this case, or give Jest a shot.

Anyway, thanks for taking a closer look at this issue!
