### ISSUE TITLE
Anything has to do to work with Vue 2.5?

### ISSUE THREAD

**Issue by whitetrefoil** [HerringtonDarkholme/av-ts#69]
I just heard about Vue v2.5 has many changes on its typings, will av-ts be compatible with it?

**Comment by HerringtonDarkholme** [comment]
Fortunately, av-ts fully support Vue2.5. See this comment for detail test 

https://github.com/vuejs/vue/pull/6391#issuecomment-323088304

**Comment by whitetrefoil** [comment]
Wow! Nice to know you're the leader of that feature.  I'll read that PR for more details later~
