### ISSUE TITLE
@Watch('value') warning: Argument type 'value' is not assignable to [string,string,string,string]

### ISSUE THREAD

**Issue by venkatperi** [HerringtonDarkholme/av-ts#79]
Any idea how to get rid of this nag?

<img width="583" alt="image" src="https://user-images.githubusercontent.com/1389947/47397021-47878800-d6fb-11e8-98bc-b9b1e28bf2a6.png">

**Comment by HerringtonDarkholme** [comment]
What's your code? I cannot give any advice without code example.

Please keep your example short and concise. I don't have time to debug your whole application.
