### ISSUE TITLE
Cant use arrays as data fields

### ISSUE THREAD

**Issue by thorning** [HerringtonDarkholme/av-ts#9]
If I use and initialise a data field as an array, it is converted to an object and can no longer be used as an array.
```
class Test extends Vue {
  list:string[] = [];
  listMethod() {
    //this.list is no longer an array, and give runtime error
    this.list.push('test')
  }
}
``` 

I can work around this, by using the `@Data` decorator, but that is not optimal, especially with multiple other data fields.

After a quick look, it could seem that the problem is that `snapshot` function in `util.js` handles arrays as objects, but I don't know if there is more to it, or if it would be correct to pass the array as value or to make a copy (properly copy to be consistent).

**Comment by HerringtonDarkholme** [comment]
Thanks! fixed in https://github.com/HerringtonDarkholme/av-ts/commit/2a510e82d9be25b8ea1551f6c6d49f4bde8c2c7c

**Comment by HerringtonDarkholme** [comment]
Also bumped to version 0.4.2
